# Generated by Django 2.1.15 on 2021-02-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_followed_by', models.IntegerField(default=0)),
                ('profile_picture_url', models.URLField()),
                ('counts_media', models.IntegerField(default=0)),
                ('counts_follow', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.TimeField()),
                ('link_to_media', models.URLField()),
                ('comments_count', models.IntegerField(default=0)),
                ('media_type', models.CharField(max_length=255)),
                ('links_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMediaLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMediaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='locations',
            field=models.ManyToManyField(to='core.InstagramMediaLocation'),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='tags',
            field=models.ManyToManyField(to='core.InstagramMediaTag'),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InstagramMedia'),
        ),
    ]
